name: telegram_database

services:
    db:
        image: postgres:latest
        hostname: telegram_database
        container_name: telegram_database
        env_file: .env
        shm_size: 8g
        environment:
            TZ: Europe/Berlin
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - .${DATABASE_FOLDER}:/var/lib/postgresql
        networks:
            - telegram-network
        ports:
            - "5432:5432"
    pgadmin:
        image: dpage/pgadmin4
        hostname: telegram_pgadmin
        container_name: telegram_pgadmin
        env_file: .env
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
            TZ: Europe/Berlin
        volumes:
            - ./pgadmin_data:/var/lib/pgadmin
        user: "${UID}:${GID}"
        ports:
            - 5050:80
        networks:
            - telegram-network
networks:
    telegram-network:
      name: telegram-network